### Posting User
POST http://localhost:3000/api/users
Content-Type: application/json

{

    "username" : "mg111222",
    "password" : "Password1",
    "password_confirmation" : "Password1",
    "height" : 5,
    "weight": 10,
    "goal_weight" : 20,
    "age" : 40,
    "public" : false,
    "water" : 3,
    "activity_level" : 1.5,
    "mf" : 5
    
}

### Show method for id 1
GET http://localhost:3000/api/users/15


### update id 1
PUT http://localhost:3000/api/users/5
Content-Type: application/json

{
    
    "username" : "mg111",
    "password" : "Password1",
    "mf" : "121",
    "public" : true

}


### delete id of 1
DELETE http://localhost:3000/api/users/1


### random user for public true
GET http://localhost:3000/api/users/random


### checking login
POST http://localhost:3000/api/users/sign_in
Content-Type: application/json

{
    "username" : "mg111",
    "password" : "Password1"
}