### Posting User
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username" : "test5",
    "password_digest" : "Password1",
    "height" : 5,
    "weight": 10,
    "goal_weight" : 20,
    "age" : 40,
    "public" : false,
    "water" : 3
}

### Show method for id 1
GET http://localhost:3000/api/users/1


### update id 1
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
    "username" : "updated_user"
}


### delete id of 1
DELETE http://localhost:3000/api/users/1


### random user for public true
GET http://localhost:3000/api/users/random
